---

- name: Deploy Mean Stack
  hosts: all
  tasks:
  - name: Install MongoDB
    yum: 
      name: mongodb
      state: present

  - name: Configure MongoDB
    copy:
      src: mongodb.conf
      dest: /etc/mongodb.conf
      owner: root
      group: root
      mode: 0644
    notify:
    - restart mongodb

