---

- name: Deploy Mean Stack
  hosts: all
  become: true
  vars:
    folder: "roles/my_awesome_role/files"
  tasks:
  
  - name: Configure MongoDB
    copy:
      src: "{{ folder }}/mongodb.repo"
      dest: /etc/yum.repos.d/mongodb.repo
      owner: root
      group: root
      mode: 0644
  - name: Install MongoDB
    yum: 
      name: mongodb-org
      state: present

  - name: Configure MongoDB
    copy:
      src: "{{ folder }}/mongodb.conf"
      dest: /etc/mongodb.conf
      owner: root
      group: root
      mode: 0644
  - name: Restart mongodb...
    service:
      name: httpd 
      state: restarted
    
